# Arithemetic Operator

In [51]:
import numpy as np 

# Addition +


In [52]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,4,6,8,10])
print("One Dimension")
print(arr1 + arr2)
print("---")

x = np.array([[1,2,3,4,5],[1,3,6,9,5]])
y = np.array([[2,4,6,8,10],[2,3,5,2,1]])
print("Two Dimension")
print(x + y)

One Dimension
[ 3  6  9 12 15]
---
Two Dimension
[[ 3  6  9 12 15]
 [ 3  6 11 11  6]]


# Subtraction -

In [53]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,4,6,8,10])
print("One Dimension")
print(arr1 - arr2)
print("---")

x = np.array([[1,2,3,4,5],[1,3,6,9,5]])
y = np.array([[2,4,6,8,10],[2,3,5,2,1]])
print("Two Dimension")
print(x - y)

One Dimension
[-1 -2 -3 -4 -5]
---
Two Dimension
[[-1 -2 -3 -4 -5]
 [-1  0  1  7  4]]


# Multiplication * 

In [54]:
arr1 = np.array([3,4,5])
arr2 = np.array([2,4,10])
print("One Dimension")
print(arr1 * arr2)
print("---")

x = np.array([[1,2,5],[1,9,5]])
y = np.array([[2,4,10],[2,3,3]])
print("Two Dimension")
print(x * y)

One Dimension
[ 6 16 50]
---
Two Dimension
[[ 2  8 50]
 [ 2 27 15]]


# Division /

In [55]:
arr1 = np.array([3,4,5])
arr2 = np.array([2,4,10])
print("One Dimension")
print(arr1 / arr2)
print("---")

x = np.array([[1,2,5],[1,9,5]])
y = np.array([[2,4,10],[2,3,3]])
print("Two Dimension")
print(x / y)

One Dimension
[1.5 1.  0.5]
---
Two Dimension
[[0.5        0.5        0.5       ]
 [0.5        3.         1.66666667]]


# Modulus %

In [56]:
arr1 = np.array([3,4,5])
arr2 = np.array([2,4,10])
print("One Dimension")
print(arr1 % arr2)
print("---")

x = np.array([[1,2,5],[1,9,5]])
y = np.array([[2,4,10],[2,3,3]])
print("Two Dimension")
print(x % y)

One Dimension
[1 0 5]
---
Two Dimension
[[1 2 5]
 [1 0 2]]


# Exponent **

In [57]:
arr1 = np.array([3,4,5])
arr2 = np.array([2,4,10])
print("One Dimension")
print(arr1**arr2)
print("---")

x = np.array([[1,2,5],[1,9,5]])
y = np.array([[2,4,10],[2,3,3]])
print("Two Dimension")
print(x**y)

One Dimension
[      9     256 9765625]
---
Two Dimension
[[      1      16 9765625]
 [      1     729     125]]
