# Numpy Array Function

# Min & Max
 - Find minimum and maximum values from array

In [5]:
import numpy as np

In [6]:
arr = np.array([100,300,200,900,700])
print("Min:", np.min(arr))
print("Max: ", np.max(arr))

Min: 100
Max:  900


In [7]:
arr = np.array([[10,20,30,40,50], [100,200,300,400,500]])
print("Min:", np.min(arr))
print("Max: ", np.max(arr))

Min: 10
Max:  500


# Axis : 0 | 1

-  Axis 0 : columns
- Axis 1 : rows

In [8]:
print("Min:", np.min(arr, axis=0))
print("Min: ", np.min(arr, axis=1))

print("Max:", np.max(arr, axis=0))
print("Max: ", np.max(arr, axis=1))

Min: [10 20 30 40 50]
Min:  [ 10 100]
Max: [100 200 300 400 500]
Max:  [ 50 500]


# argmin & argmax 
- To know the position

In [13]:
print("Min:", np.min(arr), " Position:" , np.argmin(arr))
print("Max: ", np.max(arr), " Position:",np.argmax(arr))

Min: 10  Position: 0
Max:  500  Position: 9


# sqrt 
- To find squareroot

In [18]:
print("SquareRoot:", np.sqrt(arr))

SquareRoot: [[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [10.         14.14213562 17.32050808 20.         22.36067977]]


# square
- To find square

In [19]:
print("Square:", np.square(arr))

Square: [[   100    400    900   1600   2500]
 [ 10000  40000  90000 160000 250000]]


# sin & cos
- To find sin and cos

In [21]:
print("sin:", np.sin(arr))
print('\n--\n')
print("cos:", np.cos(arr))

sin: [[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
 [-0.50636564 -0.8732973  -0.99975584 -0.85091936 -0.46777181]]

--

cos: [[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
 [ 0.86231887  0.48718768 -0.02209662 -0.52529634 -0.88384927]]


# cumsum
- sum to next 

In [23]:
arr = np.array([[10,20,30,40,50], [100,200,300,400,500]])
print("cumsum:", np.cumsum(arr))

cumsum: [  10   30   60  100  150  250  450  750 1150 1650]
