# Array Reshaping
- 1D to Multi Dimension and vice versa

    - reshape

In [37]:
import numpy as np

# 1D to Multi Dimension

In [38]:
arr = np.array([10,20,30,40,50,60,70,80])
print(arr)

[10 20 30 40 50 60 70 80]



    - Reshaping to 2D Array


In [39]:
arr2 = arr.reshape(2,4)
print(arr2)
print("Dimension", arr2.ndim)

[[10 20 30 40]
 [50 60 70 80]]
Dimension 2



    - Reshaping to 3D Array


In [40]:
arr = np.array([10,20,30,40,50,60,70,80,90,111,222,333])
arr3 = arr.reshape(2,2,3)
print(arr3)
print("Dimension", arr3.ndim)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [111 222 333]]]
Dimension 3


# Multi Dimension to 1D

     - 3D to 1D

In [41]:
arrr = arr3.reshape(-1)
print(arrr)
print("Dimension", arrr.ndim)

[ 10  20  30  40  50  60  70  80  90 111 222 333]
Dimension 1


     - 2D to 1D

In [42]:
arrr = arr2.reshape(-1)
print(arrr)
print("Dimension", arrr.ndim)


[10 20 30 40 50 60 70 80]
Dimension 1
