# Broadcasting

    - Broadcasting Rules
- Same Dimension
- (1x3) = (3x1)

In [10]:
import numpy as np

    - Same Dimension

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,4,6])
print(arr1+arr2)

print(arr1.shape)

[3 6 9]
(3,)


    - (1x3) = (3x1)

In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([[2], [4], [6]])
print(arr1+arr2)

print(arr1.shape)
print(arr2.shape)

[[3 4 5]
 [5 6 7]
 [7 8 9]]
(3,)
(3, 1)


    - Broadcasting error

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4,5])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([[2,3], [4,3], [6,3]])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 