# Array Join 

# 1. Join Arrays using concrete function

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,4,6,8])

c_arr = np.concatenate((arr1, arr2))
print(c_arr)


[1 2 3 4 2 4 6 8]


- Concate Multi Dimension Array

In [ ]:
arr1 = np.array([[1,2,3,4],[2,4,6,8]])
arr2 = np.array([[10,20,30,40],[11,22,33,44]])

c_arr = np.concatenate((arr1, arr2))
print(c_arr)

print("\n -- \n")

# Axis 1
c_arr1= np.concatenate((arr1, arr2), axis=1)
print("Axis 1: ", c_arr1)

print("\n -- \n")

# Axis 0
c_arr2= np.concatenate((arr1, arr2),axis=0)
print("Axis 0: ", c_arr2)


[[ 1  2  3  4]
 [ 2  4  6  8]
 [10 20 30 40]
 [11 22 33 44]]

 -- 

Axis 1:  [[ 1  2  3  4 10 20 30 40]
 [ 2  4  6  8 11 22 33 44]]

 -- 

Axis 0:  [[ 1  2  3  4]
 [ 2  4  6  8]
 [10 20 30 40]
 [11 22 33 44]]


# Stack function

In [ ]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([5,10,15,20])

print(np.stack((arr1,arr2)))
print("\n -- \n")
print(np.stack((arr1,arr2), axis=0))
print("\n -- \n")
print(np.stack((arr1,arr2), axis=1))

[[10 20 30 40]
 [ 5 10 15 20]]

 -- 

[[10 20 30 40]
 [ 5 10 15 20]]

 -- 

[[10  5]
 [20 10]
 [30 15]
 [40 20]]


In [ ]:
print(np.stack((arr1,arr2)))
print("\n -- \n")

[[10 20 30 40]
 [ 5 10 15 20]]

 -- 



# hstack : row

In [ ]:
print(np.hstack((arr1,arr2)))
print("\n -- \n")

[10 20 30 40  5 10 15 20]

 -- 



# vstack : colums

In [ ]:
print(np.vstack((arr1,arr2)))
print("\n -- \n")

[[10 20 30 40]
 [ 5 10 15 20]]

 -- 



# dstack : height

In [ ]:
print(np.dstack((arr1,arr2)))
print("\n -- \n")

[[[10  5]
  [20 10]
  [30 15]
  [40 20]]]

 -- 

