# Aray Split

In [44]:
import numpy as np

# Spliting 1D Array

In [45]:
arr = np.array([10,20,30,40,50,60,70,80,90,10])

arr_s = np.split(arr, 5)  # SPLIT IN 5 PARTS
print(arr_s)
print(arr_s[3])
print('\n -- \n')
arr_s = np.split(arr, 2)  # SPLIT IN 2 PARTS
print(arr_s)
print(arr_s[0])

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([90, 10])]
[70 80]

 -- 

[array([10, 20, 30, 40, 50]), array([60, 70, 80, 90, 10])]
[10 20 30 40 50]


# Spliting 2D Array

In [46]:
arr = np.array([[2,4,6,8], [5,10,15,20]])

arr_s = np.split(arr, 2)  # SPLIT IN 2 PARTS
print(arr_s)



[array([[2, 4, 6, 8]]), array([[ 5, 10, 15, 20]])]


# Spliting 3D Array

In [47]:
arr = np.array([[[2,4,6,8], [5,10,15,20], [100,200,300,400], [111,222,333,444]]])

print(arr)

arr_s = np.split(arr, 1)  # SPLIT IN  PARTS
print(arr_s)



[[[  2   4   6   8]
  [  5  10  15  20]
  [100 200 300 400]
  [111 222 333 444]]]
[array([[[  2,   4,   6,   8],
        [  5,  10,  15,  20],
        [100, 200, 300, 400],
        [111, 222, 333, 444]]])]
