In [33]:
import numpy as np 

# Sort Function
- Arrange Values

In [34]:
arr = np.array([22,13,49,33,21,80,66,25,95,100])
print(np.sort(arr))

[ 13  21  22  25  33  49  66  80  95 100]


# Where function

In [35]:
arr =  np.array([22,13,49,33,21,80,66,25,95,100])
print(np.where(arr >50 )) # return index

(array([5, 6, 8, 9]),)


# Search Sort

- return index

In [36]:
arr = np.array([10,20,30,50,60,80,100])
x = np.searchsorted(arr, 40)
y = np.searchsorted(arr, 70)
print(arr)
print(x)
print(y)

[ 10  20  30  50  60  80 100]
3
5


# extract

In [41]:
arr = np.array([10,20,30,40,50,60,70,80])
x = np.extract(arr > 40, arr)
print(x)

[50 60 70 80]
