# Update & Delete Array values

In [11]:
import numpy as np

# Insert Function

- array , index, value

In [12]:
arr = np.array([10,50,60,90])

x = np.insert(arr,3,80)
print(x)

y = np.insert(arr,(1),(20,30,40))
print(y)


[10 50 60 80 90]
[10 20 30 40 50 60 90]


# Delete Function

- array , index

In [18]:
arr = np.array([10,50,60,90])

x = np.delete(arr,1)
print(x)

y = np.delete(arr,(0,2))
print(y)


[10 60 90]
[50 90]
