# Array

In [1]:
import numpy as np 

- Numpy ndarray

In [4]:
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr)) # numpy.ndarray

[10 20 30 40 50]
<class 'numpy.ndarray'>


# Array Dimensions

- 0D Array

In [13]:
arr = np.array(10)
print(arr)
print(arr.ndim) # checking array dimension
print(type(arr))

10
0
<class 'numpy.ndarray'>


- 1D array

In [12]:
arr = np.array([100,200,300,400,500])
print(arr)
print(arr.ndim) # checking array dimension
print(type(arr))

[100 200 300 400 500]
1
<class 'numpy.ndarray'>


- 2D array


In [ ]:
arr = np.array([[10,20,30], [40,50,60]])
print(arr)
print(arr.ndim) # checking array dimension
print(type(arr))

[[10 20 30]
 [40 50 60]]
2
<class 'numpy.ndarray'>


- 3D  Array

In [18]:
arr = np.array([[[1,2,3], [11,22,33] ], [[20,30,40],[50,60,70]]])
print(arr)
print(arr.ndim) # checking array dimension
print(type(arr))

[[[ 1  2  3]
  [11 22 33]]

 [[20 30 40]
  [50 60 70]]]
3
<class 'numpy.ndarray'>


# Array indexing

- Access 1D array

In [23]:
arr1 = np.array([10,20,30,40])
print(arr1[3]) # 40

40


- Access 2D Array

In [30]:
arr2 = np.array([[100,200,300], [222,333,444]])
print(arr2[1])  # [222 333 444]
print(arr2[0][2]) # 300

[222 333 444]
300


- Access 3D Array

In [53]:
arr3 = np.array([[[11,22,33], [300,400,500], [1000,2000,3000]]])
print(arr3)
print(arr3.ndim) # checking array dimension


print(arr3[0][2][1]) # 2000


[[[  11   22   33]
  [ 300  400  500]
  [1000 2000 3000]]]
3
2000
