# Copy vs View 

The Difference Between Copy and View
-   The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

-   The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

-   The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Summary:
- Copy doesnot effect the original array
- View effect the original array

In [1]:
import numpy as np

# Copy

    - Does not effect the origional array

In [8]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[1] = 42

print(x)
print(arr)


[ 1 42  3  4  5]
[1 2 3 4 5]


# View

    - Effect the origional array

In [11]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[1] = 42

print(x)
print(arr)

[ 1 42  3  4  5]
[ 1 42  3  4  5]
