# Array

In [1]:
import numpy as np 

- Numpy ndarray

In [2]:
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr)) # numpy.ndarray

[10 20 30 40 50]
<class 'numpy.ndarray'>


# Array Dimensions

- 0D Array

In [3]:
arr = np.array(10)
print(arr)
print(arr.ndim) # checking array dimension
print(type(arr))

10
0
<class 'numpy.ndarray'>


- 1D array

In [4]:
arr = np.array([100,200,300,400,500])
print(arr)
print(arr.ndim) # checking array dimension
print(type(arr))

[100 200 300 400 500]
1
<class 'numpy.ndarray'>


- 2D array


In [5]:
arr = np.array([[10,20,30], [40,50,60]])
print(arr)
print(arr.ndim) # checking array dimension
print(type(arr))

[[10 20 30]
 [40 50 60]]
2
<class 'numpy.ndarray'>


- 3D  Array

In [6]:
arr = np.array([[[1,2,3], [11,22,33] ], [[20,30,40],[50,60,70]]])
print(arr)
print(arr.ndim) # checking array dimension
print(type(arr))

[[[ 1  2  3]
  [11 22 33]]

 [[20 30 40]
  [50 60 70]]]
3
<class 'numpy.ndarray'>


# Array indexing

- Access 1D array

In [7]:
arr1 = np.array([10,20,30,40])
print(arr1[3]) # 40

40


- Access 2D Array

In [8]:
arr2 = np.array([[100,200,300], [222,333,444]])
print(arr2[1])  # [222 333 444]
print(arr2[0][2]) # 300
print(arr2[0,2]) # 300

[222 333 444]
300
300


- Access 3D Array

In [9]:
arr3 = np.array([[[11,22,33], [300,400,500], [1000,2000,3000]]])
print(arr3)
print(arr3.ndim) # checking array dimension


print(arr3[0][2][1]) # 2000
print(arr3[0,2,1]) # 2000


[[[  11   22   33]
  [ 300  400  500]
  [1000 2000 3000]]]
3
2000
2000


# Negative Indexing

In [10]:
arr4 = np.array([100,200,300])
print(arr4[-1]) # 300
print(arr4[-2]) # 200


300
200


In [11]:
arr5 = np.array([[111,222,333], [1001,2002,3003]])
print(arr5[-1, -2]) # 2002
print(arr5[-2, -3]) # ?

2002
111
