# Array Slicing 


- Slicing in python means taking elements from one given index to another given index.

    - We pass slice instead of index like this: [start:end].

    - We can also define the step, like this: [start:end:step].

    - If we don't pass start its considered 0

    - If we don't pass end its considered length of array in that dimension

    - If we don't pass step its considered 1 

In [3]:
import numpy as np

In [17]:
arr1 = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr1)

# Slicing
newArr1 = arr1[1:6]
print(newArr1) 

# skip 1 step
newArr2 = arr1[1:8:2]
print(newArr2)

[ 10  20  30  40  50  60  70  80  90 100]
[20 30 40 50 60]
[20 40 60 80]


# Slicing 2D Array

In [ ]:
arr2 = np.array([[11,22,33,44,55,66,77,88,99], [10,20,30,40,50,60,70,80,90]])
print(arr2)

# Slicing
print("---")
newArr3 = arr2[1, 1:8:3] # 20 50 80
print(newArr3)

[[11 22 33 44 55 66 77 88 99]
 [10 20 30 40 50 60 70 80 90]]
---
[20 50 80]


# Negative Slicing

In [32]:
arr4 = np.array([100,200,300,400,500,600,700,800])
print(arr4)

# Negative Slicing
print(arr4[-1:-8:-2])

[100 200 300 400 500 600 700 800]
[800 600 400 200]
