# Numpy Array

In [19]:
import numpy as np

# Array Dimension & Shape

    - 1. Dimensions (ndim)
 - Refers to the number of levels or axes in the array.
 - Each dimension represents a different axis along which data is organized.
 - Access using the .ndim attribute.

    - 2.  Shape (shape)
 - Describes the size of the array along each dimension as a tuple of integers.
 - Each integer represents the number of elements along that axis.
 - Access using the .shape attribute.


# 0D Array (Scalar)
- A 0-dimensional array contains only a single value (a scalar).

In [20]:
arr = np.array(100)
print(arr, arr.ndim, arr.shape)

print("Array Dimension: ", arr.ndim)
print("Array Shape: ", arr.shape)

100 0 ()
Array Dimension:  0
Array Shape:  ()


# 1D Array (Vector)
- A 1-dimensional array is essentially a list of elements.

In [21]:
arr = np.array([10,20,30,40,50])
print(arr, arr.ndim, arr.shape)

print("Array Dimension: ", arr.ndim)
print("Array Shape: ", arr.shape)

[10 20 30 40 50] 1 (5,)
Array Dimension:  1
Array Shape:  (5,)


# 2D Array (Matrix)
- A 2-dimensional array is like a table with rows and columns.

In [22]:
arr = np.array([[11,22,33,44]])
print(arr)
print("Array Dimension: ", arr.ndim)
print("Array Shape: ", arr.shape)

print()

arr2 = np.array([[11,22,33,44],[10,20,30,40]])
print(arr2)
print("Array Dimension: ", arr2.ndim)
print("Array Shape: ", arr2.shape)



[[11 22 33 44]]
Array Dimension:  2
Array Shape:  (1, 4)

[[11 22 33 44]
 [10 20 30 40]]
Array Dimension:  2
Array Shape:  (2, 4)


# 3D Array (Tensor)
- A 3-dimensional array can be visualized as a stack of 2D matrices.

In [23]:
arr = np.array([[[100,200,300,400,500]]])
print(arr)
print("Array Dimension: ", arr.ndim)
print("Array Shape: ", arr.shape)

print()

arr2 = np.array([[[10,20,30],[200,300,400]]])
print(arr2)
print("Array Dimension: ", arr2.ndim)
print("Array Shape: ", arr2.shape)


[[[100 200 300 400 500]]]
Array Dimension:  3
Array Shape:  (1, 1, 5)

[[[ 10  20  30]
  [200 300 400]]]
Array Dimension:  3
Array Shape:  (1, 2, 3)


# Pre Defined Array Dimension

In [24]:
arr = np.array([100,200,300,400,500], ndmin=10)
print(arr)
print("Dimension: ", arr.ndim)

[[[[[[[[[[100 200 300 400 500]]]]]]]]]]
Dimension:  10
