# Array Types

# 1. Createing Array using Python List

In [17]:
import numpy as np 

In [2]:
l1 = ['a', 'e', 'i', 'o', 'u']
arr1 = np.array(l1)
print(l1)

['a', 'e', 'i', 'o', 'u']


In [3]:
print("Shape: ", arr1.shape)
print("dimension: ", arr1.ndim)
print("size: ", arr1.size)
print("Data Type: ", arr1.dtype)

Shape:  (5,)
dimension:  1
size:  5
Data Type:  <U1


# 2. Create an Array Using np.zeros()
 - The np.zeros() function allows us to create an array filled with all zeros. For example,


<!-- Array Types -->

In [4]:
arr1 = np.zeros(5)
print(arr1)


# 2D Array using zero function
print("2D Array")
arr2 = np.zeros((3,4))
print(arr2)

# 3D Array using zero Function
print("3D Array")
arr2 = np.zeros((3,2,3))
print(arr2)
print(arr2.ndim)


[0. 0. 0. 0. 0.]
2D Array
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
3D Array
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
3


In [5]:
print("Shape: ", arr1.shape)
print("dimension: ", arr1.ndim)
print("size: ", arr1.size)
print("Data Type: ", arr1.dtype)

Shape:  (5,)
dimension:  1
size:  5
Data Type:  float64


# 3. Create an Array Using np.Ones()
 - The np.ones() function allows us to create an array filled with all ones. For example,


In [6]:
arr1 = np.ones(5)
print(arr1)


# 2D Array using zero function
print("2D Array")
arr2 = np.ones((3,4))
print(arr2)

# 3D Array using zero Function
print("3D Array")
arr2 = np.ones((4,2,3))
print(arr2)


[1. 1. 1. 1. 1.]
2D Array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3D Array
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 4. Create an Array With np.arange()
 - The np.arange() function returns an array with values within a specified interval. For example,

In [7]:
arr1 = np.arange(5,10,2)
print(arr1)

[5 7 9]


# 5.Create an Array With np.random.rand()
 - The np.random.rand() function is used to create an array of random numbers.

In [8]:
arr1 = np.random.rand(5)*1000
ar = arr1.astype(int)
print(ar)
print(arr1)


# 2D Array using zero function
print("2D Array")
arr2 = np.random.rand(3,3)
print(arr2)

# 3D Array using zero Function
print("3D Array")
arr2 = np.random.rand(4,4,3)*1000

print(arr2)





[159 236 348 914 749]
[159.49157349 236.40960392 348.36141126 914.58265165 749.38094688]
2D Array
[[0.90465885 0.29762314 0.72698662]
 [0.12043675 0.29985677 0.6613047 ]
 [0.28729516 0.56164341 0.26169805]]
3D Array
[[[8.20888150e+02 7.31024141e+01 7.20149057e+02]
  [3.71452402e+02 6.19245705e+02 7.06201568e+02]
  [3.01685302e+02 2.63780465e+02 9.85441512e+02]
  [2.26892799e+02 4.05457331e+02 7.84779221e+02]]

 [[1.05901971e+02 5.71645822e+02 1.21960123e+01]
  [8.77250890e+02 3.54397545e+02 1.29704523e+02]
  [7.76447707e+02 4.73603594e+00 8.87296131e+02]
  [3.15481445e+02 4.49397305e+02 5.71016429e+02]]

 [[5.41511142e+01 4.05302952e+02 7.92169150e+02]
  [1.66687071e+01 5.10582270e+02 4.00768080e+02]
  [3.25136524e+02 4.02564237e+02 8.48031219e-01]
  [7.80632012e+02 9.23509893e+02 9.47611646e+02]]

 [[7.96702297e+02 5.95594509e+02 5.99646743e+02]
  [8.08655663e+02 9.18276160e+02 6.46279625e+02]
  [1.16573653e+02 8.68125374e+02 1.08087440e+02]
  [4.36061791e+02 8.15758516e+02 9.45202816

In [9]:
print("Removing Decimals")
arrr = arr2.astype(int)
print(arrr)

Removing Decimals
[[[820  73 720]
  [371 619 706]
  [301 263 985]
  [226 405 784]]

 [[105 571  12]
  [877 354 129]
  [776   4 887]
  [315 449 571]]

 [[ 54 405 792]
  [ 16 510 400]
  [325 402   0]
  [780 923 947]]

 [[796 595 599]
  [808 918 646]
  [116 868 108]
  [436 815 945]]]


# 6. Create an Empty NumPy Array
 - To create an empty NumPy array, we use the np.empty() function. For example,

In [10]:
arr1 = np.empty(15)
print(arr1)

[6.56541534e+199 1.24413145e+137 2.28683327e+243 3.65875442e+233
 9.08254283e+223 1.69595973e+199 2.28191497e+232 2.25565487e+137
 2.58142444e+161 9.88627443e+170 1.10020917e-071 7.66577641e+218
 2.06738284e-027 2.55616198e+161 9.88585060e+170]


    - If we look into the output of the code, we can see the empty array is actually not empty, it has some values in it.

    - It is because although we are creating an empty array, NumPy will try to add some value to it. The values stored in the array are arbitrary and have no significance.

# 7. Diagonal Array

In [11]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
arr = np.eye(3,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [13]:
arr = np.eye(6,6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


        - All Diagonal elements are filled by 1

# 8. Linspace Array

In [14]:
arr = np.linspace(0,10,num=3) # 0 TO 10 and total numbers should be 3
print(arr)

[ 0.  5. 10.]


In [15]:
arr = np.linspace(0,10,num=5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
arr = np.linspace(5,20,num=4)
print(arr)

[ 5. 10. 15. 20.]
