# Numpy Random Array

 - 1. rand : Generates Random numbers between 0 and 1 (uniform distribution).
 - 2. randn : Grenerates Random numbers following a normal distribution (mean = 0, std = 1).
 - 3. ranf : Generates Random floats between 0 and 1 (similar to rand, but accepts a shape as an argument instead of dimensions).
 - 4. randint

In [46]:
import numpy as np

# 1. rand function
- Generates Random numbers between 0 and 1 (uniform distribution).

In [47]:
arr = np.random.rand(3)
print(arr)

[0.83141271 0.29676675 0.20501769]


# 2. randn function
- Random numbers following a normal distribution (mean = 0, std = 1).

In [77]:
arr = np.random.randn(5,3)
print(arr)
print(arr.dtype)

[[0.61415852 0.23083463 0.80969231]
 [1.50786582 0.3319243  3.07063886]
 [0.34361322 0.68278809 0.49146111]
 [1.11155027 2.99352376 1.23571402]
 [0.4768051  0.97722687 0.86766667]]
float64


# 3. ranf function
- Random floats between 0 and 1 (similar to rand, but accepts a shape as an argument instead of dimensions).

In [79]:
arr = np.random.ranf(3)
print(arr)
print(arr.dtype)

[0.66206912 0.19523695 0.06221253]
float64


# 4. randint function
- Random integers from low (inclusive) to high (exclusive).

        - Usage: numpy.random.randint(low, high, size)

In [81]:
arr = np.random.randint(10,20,3)
print(arr)
print(arr.ndim)

[12 10 18]
1


# Extras

In [83]:
arr = np.random.randint(5,20,3)*10
print(arr)

[170  70  90]
